# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: test

on:
  push: # run this workflow on every push
  # pull_request: # run this workflow on every pull_request

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Verify all Gobra files
        uses: jogasser/gobra-action@develop
        with:
          imageName: ghcr.io/jogasser/gobra
          imageVersion: gobra-action
          chop: 10
          caching: 1
          viperBackend: VSWITHSILICON
          globalTimeout: 13h
          packageTimeout: 10h
      - name: Archive cache
        uses: actions/upload-artifact@v2
        with:
          name: cache
          path: ${{ runner.workspace }}/.gobra/cache.json
      - name: Archive statistics report
        uses: actions/upload-artifact@v2
        with:
          name: cache
          path: ${{ runner.workspace }}/.gobra/stats.json     
          
